name: Deploy to Railway

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Debug Environment Variables
        run: echo "RAILWAY_PROJECT_ID is set to: ${{ secrets.RAILWAY_PROJECT_ID }}"

      - name: Link Railway Project
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} --verbose

      - name: Deploy to Staging
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway up --environment staging --verbose

  deploy_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Debug Environment Variables
        run: echo "RAILWAY_PROJECT_ID is set to: ${{ secrets.RAILWAY_PROJECT_ID }}"

      - name: Link Railway Project
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway link --project ${{ secrets.RAILWAY_PROJECT_ID }} --verbose

      - name: Deploy to Production
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: railway up --environment production --verbose
