name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  staging:
    runs-on: ubuntu-latest
    name: Deploy to Staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy to Railway (Staging)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_STAGE_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
