name: Deploy to Railway

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Railway CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh

      - name: Link Railway Project
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          railway link --project $RAILWAY_PROJECT_ID

      - name: Deploy to Staging
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_ENVIRONMENT: staging
        run: |
          railway up

  deploy_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Railway CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh

      - name: Link Railway Project
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          railway link --project $RAILWAY_PROJECT_ID

      - name: Deploy to Production
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_ENVIRONMENT: production
        run: |
          railway up
